sudo: required

dist: trusty

services:
  - docker

language: go

go:
  - 1.11
  - tip

before_install:
  # Bazel requires JDK8
  - sudo apt-get install oracle-java8-installer

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel

install:
  - go get -u golang.org/x/lint/golint

script:
  - make deps

  # Verify that all source files are correctly formatted.
  - gofmt -e -l .

  # Verify go lint, go vet, gofmt, go fix.
  - make criticism
  - make pretty

  # Verify that a vanilla Go build still works.
  - make bin

  # Verify that there aren't issues with correctness...
  - go build -a -v -race main.go

  # Verify tests.
  - make test-bin
  - go test -timeout 10s -v -tags=travis ./...

  # Verify that Bazel builds still work.
  - bazel clean
  - bazel build //...
  - bazel test //...
